language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
env:
    - TEST=test
matrix:
    include:
        - python: 2.7
          env: PYLAMA=1
install:
    - if [[ `python -c "import sys; print(int(sys.version_info < (2, 7)))"` == "1" ]]; then pip install --use-mirrors unittest2; fi
    - pip install -v --use-mirrors .
    - pip install --use-mirrors pylama
before_script:
    - python symlinkcdll.py
    - PYSTACIA_LOG=1 python -c "from pystacia.api import get_dll; get_dll(False)"
    - python -c "from pystacia import magick; from pprint import pprint; pprint(magick.info())"
script:
    - if [[ $TEST == "test" ]]; then nosetests; fi
    - if [[ $PYLAMA == "1" ]]; then cd pystacia && pylama; fi
